USE SCHOOL;
CREATE TABLE COURSE 
( IDCOURSE INTEGER NOT NULL,  
  TITLE CHAR(30) NOT NULL, 
  STREAM CHAR(30) NOT NULL,
  TYPE CHAR(30) NOT NULL,
  STARTDATE DATE ,
  ENDDATE DATE,
  CONSTRAINT pk1 PRIMARY KEY(IDCOURSE) 
 );