USE SCHOOL;
SELECT S.FIRSTNAME  AS STUDENT_NAME,S.LASTNAME  AS STUDENT_LASTNAME,C.TITLE AS COURSE_TITLE,C.STREAM AS COURSE_STREAM,C.TYPE AS COURSE_TYPE,A.DESCRIPTION AS ASSIG_DESCR,A.SUBDATETIME AS ASSIG_SUBDATE FROM 
STUDENT S INNER JOIN COURSE_STUDENT CS ON S.IDSTUDENT=CS.SID
INNER JOIN COURSE C ON CS.CID=C.IDCOURSE
INNER JOIN COURSE_ASSIGNMENT CA ON C.IDCOURSE=CA.IDC
INNER JOIN ASSIGNMENT A ON CA.IDA=A.IDASSIGNMENT;