USE SCHOOL;
SELECT S.FIRSTNAME,S.LASTNAME, COUNT(*) AS COURSES
FROM COURSE_STUDENT CS
INNER JOIN COURSE C ON CS.CID= C.IDCOURSE
INNER JOIN STUDENT S ON CS.SID= S.IDSTUDENT
GROUP BY S.FIRSTNAME,S.LASTNAME HAVING COUNT(*)>1
;