USE SCHOOL;
CREATE TABLE ASSIGNMENT
( IDASSIGNMENT INTEGER NOT NULL,  
  DESCRIPTION CHAR(30) , 
  SUBDATETIME DATE NOT NULL,
  ORALMARK INTEGER ,
  TOTALMARK INTEGER ,
  CONSTRAINT pk2 PRIMARY KEY(IDASSIGNMENT) 
 );