USE SCHOOL;
CREATE TABLE TRAINER 
( IDTRAINER INTEGER NOT NULL,  
  FIRSTNAME  CHAR(30) NOT NULL, 
  LASTNAME CHAR(30) NOT NULL,
  SUBJECT CHAR(30) NOT NULL,
  COURSEID INTEGER ,
  CONSTRAINT pk4 PRIMARY KEY(IDTRAINER),
  CONSTRAINT fk_COURSEID FOREIGN KEY(COURSEID) REFERENCES COURSE(IDCOURSE) 
 );