USE SCHOOL;
CREATE TABLE COURSE_STUDENT
 (  
 CID INTEGER NOT NULL, 
 SID INTEGER NOT NULL, 
 CONSTRAINT pk5 PRIMARY KEY(CID,SID), 
 CONSTRAINT fk_CID FOREIGN KEY(CID) REFERENCES COURSE(IDCOURSE), 
 CONSTRAINT fk_SID FOREIGN KEY(SID) REFERENCES STUDENT(IDSTUDENT) 
 );