USE SCHOOL;
CREATE TABLE COURSE_ASSIGNMENT
 (  
 IDC INTEGER NOT NULL, 
 IDA INTEGER NOT NULL, 
 CONSTRAINT pk6 PRIMARY KEY(IDC,IDA), 
 CONSTRAINT fk_IDC FOREIGN KEY(IDC) REFERENCES COURSE(IDCOURSE), 
 CONSTRAINT fk_IDA FOREIGN KEY(IDA) REFERENCES ASSIGNMENT(IDASSIGNMENT) 
 );